project:
  type: website
  output-dir: _site

website:
  title: Science at Fishbourne
  favicon: /images/microscope.svg
  navbar:
    title: false
    logo: "/images/logo-circle.png"
    left:
      - href: index.qmd
        text: Home
      - href: next/next.qmd
        text: Next Talk
      - previous.qmd
      - news.qmd
      - subscribe.qmd
      - contact.qmd
      - location.qmd
    right:
      - about.qmd

format:
  html:
    author-title: Speaker(s)
    published-title: Presentation Date
    theme:
      - flatly
      - custom.scss
    css: styles.css
    title-block-banner: true
